- name: variables from files
  hosts: mongodb
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "Hi I am {{NAME}}, Date of birth is: {{DOB}}, born in: {{BORN}}"